{
 "title": "Projeto Korp - http-server-projeto-korp",
 "tags": [ "projeto-korp" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Disponibilidade do Serviço",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_server_projeto_korp_up", "legendFormat": "up" }
   ]
  },
  {
   "title": "Volume de Requisições (por segundo)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_server_projeto_korp_requests_total[1m])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Total de Requisições (janela selecionada)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_projeto_korp_requests_total[$__range]))",
     "legendFormat": "total"
    }
   ]
  }
 ]
}